version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.39"
    - "8.40"
    - "8.41"
    - 8.41.1
  - dependency-name: org.eclipse.jetty:jetty-util-ajax
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-security
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-client
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-proxy
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-servlets
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-continuation
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty:jetty-http
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: io.netty:netty-all
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
    versions:
    - 2.11.3
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-cbor
    versions:
    - 2.11.3
  - dependency-name: com.fasterxml.jackson.module:jackson-module-jaxb-annotations
    versions:
    - 2.11.3
  - dependency-name: com.fasterxml.jackson.module:jackson-module-scala_2.12
    versions:
    - 2.11.3
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.11.3
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.11.3
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.11.3
